services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ropa
      POSTGRES_PASSWORD: ropa
      POSTGRES_DB: ropa
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
